services:
  neo4j:
    image: neo4j:5.8 # Versión de Neo4J
    container_name: neo4j-container
    ports:
      - "7474:7474" # Puerto para la interfaz web
      - "7687:7687" # Puerto para el protocolo Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test123456789 # Usuario y contraseña
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes # Aceptar el acuerdo de licencia
volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  
